name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Django-cicd/requirements.txt
        pip install coverage
    - name: Run Tests
      run: |
        python Django-cicd/manage.py test app
        coverage run Django-cicd/app/tests.py
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 49a5cba12304aeae64c950b19823d0339d165a6f40057faefab40970483a69a4
      with:
        coverageCommand: coverage report
        debug: true
